### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by zorvan** [appliedtopology/ctl#4]
When I Try to produce big complexes (i.e 1G Bytes) neither persistence nor concurrent_homology run correctly. they both crash.

**Comment by rhl-** [comment]
Can you please paste the error?

**Comment by poulson** [comment]
It's worth keeping in mind that, on many systems, ``new`` will not throw an ``std::bad_alloc`` error and will instead happily return a buffer that is too small (I believe this is called an "optimistic" policy). If the crash only occurs for large problem sizes, this is a likely candidate.

**Comment by rhl-** [comment]
@poulson i'm not sure how @zorvan is using the tools. This is likely to occur if one hands incorrect inputs to these binaries, even on small datasizes. I've also recently made some changes in master. At any rate, I need more info before jumping to any conclusions.

**Comment by rhl-** [comment]
@zorvan i just pushed an update that fixes a major error that I introduced into the chain_complex structure used in those binaries. Please check if things work now. Note, the File I/O routines in my code are rudimentary, so File I/O will be slow.
